name: tmr_flashcard_app
description: "A customizable TMR flashcard app."
publish_to: 'none'
version: 1.0.0+1

android:
  package: com.example.tmr_learning_app
  compileSdkVersion: 34
  minSdkVersion: 21

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  path_provider: ^2.0.15
  shared_preferences: ^2.0.0
  auto_size_text: ^3.0.0
  wakelock_plus: ^1.1.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/CueSound1_normalized.wav
    - assets/CueSound2_normalized.wav
    - assets/CueSound3_normalized.wav
    - assets/CueSound4_normalized.wav
    - assets/CueSound5_normalized.wav
    - assets/CueSound6_normalized.wav
    - assets/CueSound7_normalized.wav
    - assets/CueSound8_normalized.wav
    - assets/CueSound9_normalized.wav
    - assets/CueSound10_normalized.wav
    - assets/CueSound11_normalized.wav
    - assets/CueSound12_normalized.wav
    - assets/CueSound13_normalized.wav
    - assets/CueSound14_normalized.wav
    - assets/CueSound15_normalized.wav
    - assets/CueSound16_normalized.wav
    - assets/CueSound17_normalized.wav
    - assets/CueSound18_normalized.wav
    - assets/CueSound19_normalized.wav
    - assets/CueSound20_normalized.wav
    - assets/CueSound21_normalized.wav
    - assets/CueSound22_normalized.wav
    - assets/CueSound23_normalized.wav
    - assets/CueSound24_normalized.wav
    - assets/CueSound25_normalized.wav
    - assets/CueSound26_normalized.wav
    - assets/CueSound27_normalized.wav
    - assets/CueSound28_normalized.wav
    - assets/CueSound29_normalized.wav
    - assets/CueSound30_normalized.wav
    - assets/CueSound31_normalized.wav
    - assets/CueSound32_normalized.wav
    - assets/CueSound33_normalized.wav
    - assets/CueSound34_normalized.wav
    - assets/CueSound35_normalized.wav
    - assets/CueSound36_normalized.wav
    - assets/CueSound37_normalized.wav
    - assets/CueSound38_normalized.wav
    - assets/CueSound39_normalized.wav
    - assets/CueSound40_normalized.wav
    - assets/CueSound41_normalized.wav
    - assets/CueSound42_normalized.wav
    - assets/CueSound43_normalized.wav
    - assets/CueSound44_normalized.wav
    - assets/CueSound45_normalized.wav
    - assets/CueSound46_normalized.wav
    - assets/CueSound47_normalized.wav
    - assets/CueSound48_normalized.wav
    - assets/CueSound49_normalized.wav
    - assets/CueSound50_normalized.wav
    - assets/CueSound51_normalized.wav
    - assets/CueSound52_normalized.wav
    - assets/CueSound53_normalized.wav
    - assets/CueSound54_normalized.wav
    - assets/CueSound55_normalized.wav
    - assets/CueSound56_normalized.wav
    - assets/CueSound57_normalized.wav
    - assets/CueSound58_normalized.wav
    - assets/CueSound59_normalized.wav
    - assets/CueSound60_normalized.wav
    - assets/CueSound61_normalized.wav
    - assets/CueSound62_normalized.wav
    - assets/CueSound63_normalized.wav
    - assets/CueSound64_normalized.wav
    - assets/CueSound65_normalized.wav
    - assets/CueSound66_normalized.wav
    - assets/CueSound67_normalized.wav
    - assets/CueSound68_normalized.wav
    - assets/CueSound69_normalized.wav
    - assets/CueSound70_normalized.wav
    - assets/CueSound71_normalized.wav
    - assets/CueSound72_normalized.wav
    - assets/CueSound73_normalized.wav
    - assets/CueSound74_normalized.wav
    - assets/CueSound75_normalized.wav
    - assets/CueSound76_normalized.wav
    - assets/CueSound77_normalized.wav
    - assets/CueSound78_normalized.wav
    - assets/CueSound79_normalized.wav
    - assets/CueSound80_normalized.wav
    - assets/CueSound81_normalized.wav
    - assets/CueSound82_normalized.wav
    - assets/CueSound83_normalized.wav
    - assets/CueSound84_normalized.wav
    - assets/CueSound85_normalized.wav
    - assets/CueSound86_normalized.wav
    - assets/CueSound87_normalized.wav
    - assets/CueSound88_normalized.wav
    - assets/CueSound89_normalized.wav
    - assets/CueSound90_normalized.wav
    - assets/CueSound91_normalized.wav
    - assets/CueSound92_normalized.wav
    - assets/CueSound93_normalized.wav
    - assets/CueSound94_normalized.wav
    - assets/CueSound95_normalized.wav
    - assets/CueSound96_normalized.wav
    - assets/CueSound97_normalized.wav
    - assets/CueSound98_normalized.wav
    - assets/CueSound99_normalized.wav
    - assets/CueSound100_normalized.wav
    - assets/CueSound101_normalized.wav
    - assets/CueSound102_normalized.wav
    - assets/CueSound103_normalized.wav
    - assets/CueSound104_normalized.wav
    - assets/CueSound105_normalized.wav
    - assets/CueSound106_normalized.wav
    - assets/CueSound107_normalized.wav
    - assets/CueSound108_normalized.wav
    - assets/CueSound109_normalized.wav
    - assets/CueSound110_normalized.wav
    - assets/CueSound111_normalized.wav
    - assets/CueSound112_normalized.wav
    - assets/CueSound113_normalized.wav
    - assets/CueSound114_normalized.wav
    - assets/CueSound115_normalized.wav
    - assets/CueSound116_normalized.wav
    - assets/CueSound117_normalized.wav
    - assets/CueSound118_normalized.wav
    - assets/CueSound119_normalized.wav
    - assets/CueSound120_normalized.wav
    - assets/soundcheck1_normalized.wav
    - assets/soundcheck2_normalized.wav
    - assets/soundcheck3_normalized.wav
    - assets/soundcheck4_normalized.wav
    - assets/soundcheck5_normalized.wav
    - assets/soundcheck6_normalized.wav
    - assets/CueSound121_normalized.wav
    - assets/CueSound122_normalized.wav
    - assets/CueSound123_normalized.wav
    - assets/CueSound124_normalized.wav
    - assets/CueSound125_normalized.wav
    - assets/CueSound126_normalized.wav
    - assets/CueSound127_normalized.wav
    - assets/CueSound128_normalized.wav
    - assets/CueSound129_normalized.wav
    - assets/CueSound130_normalized.wav
    - assets/CueSound131_normalized.wav
    - assets/CueSound132_normalized.wav
    - assets/CueSound133_normalized.wav
    - assets/CueSound134_normalized.wav
    - assets/CueSound135_normalized.wav
    - assets/CueSound136_normalized.wav
    - assets/CueSound137_normalized.wav
    - assets/CueSound138_normalized.wav
    - assets/CueSound139_normalized.wav
    - assets/CueSound140_normalized.wav
    - assets/CueSound141_normalized.wav
    - assets/CueSound142_normalized.wav
    - assets/CueSound143_normalized.wav
    - assets/CueSound144_normalized.wav
    - assets/CueSound145_normalized.wav
    - assets/CueSound146_normalized.wav
    - assets/CueSound147_normalized.wav
    - assets/CueSound148_normalized.wav
    - assets/CueSound149_normalized.wav
    - assets/CueSound150_normalized.wav
    - assets/CueSound151_normalized.wav
    - assets/CueSound152_normalized.wav
    - assets/CueSound153_normalized.wav
    - assets/CueSound154_normalized.wav
    - assets/CueSound155_normalized.wav
    - assets/CueSound156_normalized.wav
    - assets/CueSound157_normalized.wav
    - assets/CueSound158_normalized.wav
    - assets/CueSound159_normalized.wav
    - assets/CueSound160_normalized.wav
    - assets/CueSound161_normalized.wav
    - assets/CueSound162_normalized.wav
    - assets/CueSound163_normalized.wav
    - assets/CueSound164_normalized.wav
    - assets/CueSound165_normalized.wav
    - assets/CueSound166_normalized.wav
    - assets/CueSound167_normalized.wav
    - assets/CueSound168_normalized.wav
    - assets/CueSound169_normalized.wav
    - assets/CueSound170_normalized.wav
    - assets/CueSound171_normalized.wav
    - assets/CueSound172_normalized.wav
    - assets/CueSound173_normalized.wav
    - assets/CueSound174_normalized.wav
    - assets/CueSound175_normalized.wav
    - assets/CueSound176_normalized.wav
    - assets/CueSound177_normalized.wav
    - assets/CueSound178_normalized.wav
    - assets/CueSound179_normalized.wav
    - assets/CueSound180_normalized.wav
    - assets/CueSound181_normalized.wav
    - assets/CueSound182_normalized.wav
    - assets/CueSound183_normalized.wav
    - assets/CueSound184_normalized.wav
    - assets/CueSound185_normalized.wav
    - assets/CueSound186_normalized.wav
    - assets/CueSound187_normalized.wav
    - assets/CueSound188_normalized.wav
    - assets/CueSound189_normalized.wav
    - assets/CueSound190_normalized.wav
    - assets/CueSound191_normalized.wav
    - assets/CueSound192_normalized.wav
    - assets/CueSound193_normalized.wav
    - assets/CueSound194_normalized.wav
    - assets/CueSound195_normalized.wav
    - assets/CueSound196_normalized.wav
    - assets/CueSound197_normalized.wav
    - assets/CueSound198_normalized.wav
    - assets/CueSound199_normalized.wav
    - assets/CueSound200_normalized.wav
    - assets/CaveAmbience.wav
    - assets/WaterfallAmbience.wav 
    - assets/BirdAmbience.wav